# Generated by Django 3.2.12 on 2022-04-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_group_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member',
        ),
    ]
