# Generated by Django 3.2 on 2022-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_user_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
